version: '3'
services:
    client:
        build: client/
        volumes:
            - ./client:/client
        ports:
            - 3000:3000
        tty: true
    server:
        build: server/
        volumes:
            - ./server:/server
        ports:
            - 9000:9000
    database:
        image: 'postgres'
        env_file:
            - database.env
        volumes:
            - database-data:/var/lib/postgresql/data/
        ports:
            - '35432:5432'
volumes:
    database-data: